---
# tasks file for tomcat
  - name: install java
    package: name=openjdk-8-jdk

  - name: add group "tomcat"
    group: name=tomcat

  - name: add user "tomcat"
    user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
    become: True
    become_method: sudo

  - name: Extract tomcat archive
    unarchive:
      src: http://apache.ip-connect.vn.ua/tomcat/tomcat-{{ tomcat_global_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
      dest: /opt/
      remote_src: yes
      
  - name: Symlink install directory
    file: src=/opt/apache-tomcat-{{ tomcat_version }} path=/usr/share/tomcat state=link

  - name: Change ownership of Tomcat installation
    file: path=/opt/apache-tomcat-{{ tomcat_version }} owner=tomcat group=tomcat state=directory recurse=yes

  - name: Add config users
    template: src=tomcat-users.xml dest=/usr/share/tomcat/conf 

  - name: Install Tomcat init script
    copy: src=tomcat-initscript.sh dest=/etc/systemd/system/tomcat.service mode=0755
  
  - name: Start Tomcat
    service: name=tomcat state=started enabled=yes